name: Units Benchmark
on:
        push:
                branches:
                        - main
jobs:
        benchmark:
                name: Check Units performane
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: Cache Google Benchmark
                          uses: actions/cache@v1
                          with:
                                  path: icu4c/source/test/googlebenchmarktest/benchmark
                                  key: ${{ runner.os }}-googlebenchmark-v1.5.5
                        - name: Run units benchmark
                          run: cd icu4c/source/test/googlebenchmarktest && make json
                        - name: Store benchmark result
                          uses: rhysd/github-action-benchmark@v1
                          with:
                                  name: Units Benchmark
                                  tool: 'googlecpp'
                                  output-file-path: icu4c/source/test/googlebenchmarktest/benchmark_result.json
                                  # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
                                  github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
                                  auto-push: true
                                  # Show alert with commit comment on detecting possible performance regression
                                  alert-threshold: '200%'
                                  comment-on-alert: true
                                  fail-on-alert: true
                                  alert-comment-cc-users: '@younies'

